### ISSUE TITLE
Chrome web store

### ISSUE THREAD

**Issue by CorvetteCole** [krmax44/Playify#1]
Hey I have a chrome web store Dev account that I can add you as a maintainer on and you can publish the extension through there as proxy. It's only like $5 anyway but just offering

**Comment by krmax44** [comment]
I'm currently getting myself a credit card for this, live in Germany and credit cards are not as common here. Damn it Google - why no PayPal?! Thank you anyway!

**Comment by tuhoojabotti** [comment]
I don't have a credit card either, but I was able to create my account with a Visa Electron card. (Not sure if you use those either in Germany.)

**Comment by krmax44** [comment]
@tuhoojabotti seems to be unavailable here...
