### ISSUE TITLE
Transfers only the first 100 songs of a playlist before stopping

### ISSUE THREAD

**Issue by SirDufus** [krmax44/Playify#10]
I thought it was working great until I realised that it always transfers a maximum of 100 songs in every playlist I create. 

Don't know if others are experiencing this bug as well, but I can't find any documentation that mentions a 100 song limit so am thinking something is wrong.

**Comment by krmax44** [comment]
see https://github.com/krmax44/Playify-Transfer/issues/3

**Comment by krmax44** [comment]
now transfers more than 100 songs in v3
