### ISSUE TITLE
Transfer button always says 'Please Wait'

### ISSUE THREAD

**Issue by SirDufus** [krmax44/Playify#11]
You asked me to open an issue when I reported my 'please wait' problem on Reddit yesterday. There wasn't much in the console:

`No data in hash. commons.js:1 
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of this.data.tracks.push
    at u.default.get.then.e (commons.js:1)`

You mentioned something about having an api limit of 100 songs in your reply and having to loop in the background. You should know the playlist I am trying to convert only has 84 songs.

**Comment by krmax44** [comment]
Had this issue during development and thought I fixed it... It's because I push the new tracks to the track array using a spread operator, which throws an error when the new array isn't an iterable (in this case because it doesn't exist). Will fix when my vacation is over.
