### ISSUE TITLE
Issues installing

### ISSUE THREAD

**Issue by staplrbus** [krmax44/Playify#6]
i know i'm doing something clearly wrong...
>>> $ pip install gmusicapi
  File "<stdin>", line 1
    $ pip install gmusicapi
    ^
SyntaxError: invalid syntax
>>> $ pip install websocket_server
  File "<stdin>", line 1
    $ pip install websocket_server
    ^
SyntaxError: invalid syntax
>>> $ python password.py

**Comment by krmax44** [comment]
Firstly, please post these issues to [the Playify Transfer repo](https://github.com/krmax44/Playify-Transfer).

It seems like you don't have `pip` installed.

**Comment by staplrbus** [comment]
i installed pip and can get the first two commands to work perfectly by removing the $ 
however the third command ($ python password.py) doesn't work for me, it says that there is no such file or directory

**Comment by krmax44** [comment]
Don't type in the $. It is already given by your terminal.

**Comment by krmax44** [comment]
Don't type in the $.

**Comment by ghost** [comment]
I'm aware of that now, but when i type in python password.py it says

/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'password.py': [Errno 2] No such file or directory

**Comment by krmax44** [comment]
Firstly, you need Python 3, so use `python3 password.py` after installing it.
Also, the terminal needs to be in the same directory as the files.
