### ISSUE TITLE
Syntax error when trying to install playlist transfer?

### ISSUE THREAD

**Issue by restinginlove** [krmax44/Playify#7]
Hi, I am running galliumOS on a chromebook and was using the linux instructions to install the playify transfer, but get this when running the password command:
Traceback (most recent call last):
File "password.py", line 2, in <module>
    text_file.write(input("Set a password: "))
  File "<string>", line 1
  passwordcensored
              ^
SyntaxError: unexpected EOF while parsing

and then this when trying to run playlify transfer:
python playify-transfer.py
  File "playify-transfer.py", line 4
SyntaxError: Non-ASCII character '\xe2' in file playify-transfer.py on line 4, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

I'm still a linux/command line/python newbie (hell I had to google to figure out that I could use pip3 instead of pip to get those commands to work, I kept getting "command not found" with just pip) but I'm not sure how to go about fixing these issues, if they're user error?

Thank you for your help!

**Comment by krmax44** [comment]
Please note, these kind of bugs need to be submitted in the Transfer repo:
https://github.com/krmax44/Playify-Transfer

It seems like you are using Python 2.3. However, Python 3.x is required for Playify Transfer.

Run this command to install Py3:
`sudo apt-get install python3`

Then, run:
`python3 password.py`
...set your password, then:
`python3 playify-transfer.py`

**Comment by festivefirstname** [comment]
Leave it to me to post this in the wrong area, I'm sorry! And it looks like I have python 3.5.2 installed, but I ran the install command anyway just to be sure and everything seems to be working perfectly with the python3 commands now, thank you!
