### ISSUE TITLE
Feature: use specific logged-in Google account link

### ISSUE THREAD

**Issue by joeburdick** [krmax44/Playify#8]
Sorry if this is the wrong place to request this as a feature.

I am always logged into multiple Google accounts and my primary one on my work machine is my work email (not my GPM-subscribed account) so my GPM bookmark looks like: https://play.google.com/music/listen?u=1#/home

It'd be nice to configure Playify to use a particular account so that the u=1 can be added to links appropriately.

**Comment by krmax44** [comment]
I'd probably go a step further and allow completely custom URLs to be added, so that even users of exotic streaming services can take advantage of Playify.

**Comment by krmax44** [comment]
added in v3
